TrueBrain/TrueWiki

truewiki/__main__.py, truewiki/metadata.py
This means that is someone saves a page that takes 10+ seconds
to reanalyze the metadata, it no longer blocks the webinterface.
Instead, the update is delayed heavily, so someone could add
a category that only shows up seconds later. That is the trade-off
here.
=> Add: analyze the metadata in another process, so we don't block the main

.dockerignore, .gitignore, Dockerfile, README.md, truewiki/storage/local.py
It now sets the cache file for metadata in a folder that is strongly
suggested to volume mount. This means a second start is a lot faster
(from 200s to 0.1s).
=> Fix: make the instructions for Docker by default a bit quicker after first run

truewiki/storage/github.py
This is needed as --storage-github-url can be a git@github.com URL,
which does not allow HTTPS visit. By setting --storage-github-history-url
you can set the URL used for GitHub history, which should be like
https://github.com/username/repository.
=> Fix: allow setting a different URL for the history on GitHub

templates/Edit.mediawiki, truewiki/views/edit.py, truewiki/views/preview.py, truewiki/views/source.py, truewiki/web_routes.py
Additionally, do not sneak in "Main Page" when pressing preview;
it is annoying and unnneeded.
=> Fix: remember the page-name when previewing

templates/Edit.mediawiki, templates/Error.mediawiki, templates/Login.mediawiki, templates/Page.mediawiki, templates/Source.mediawiki, truewiki/content/breadcrumb.py, truewiki/views/license.py, truewiki/web_routes.py, truewiki/wiki_page.py
This is a special-case URL, as we wouldn't want anyone to
translate it, ideally it should be in the root of the data-folder,
and nobody is allowed to edit it. This is all made possible by
making the page a special case.
=> Add: render /License with the content of LICENSE.mediawiki

truewiki/views/edit.py, truewiki/web_routes.py
Otherwise wikitexthtml fails to detect \n\n, to insert `<p>`'s.
=> Fix: also strip \r from preview render

templates/Edit.mediawiki, templates/Page.mediawiki, templates/Source.mediawiki, truewiki/views/edit.py, truewiki/views/preview.py, truewiki/views/source.py
This should make it easier to see and fix any page name error.
=> Fix #48: report errors about wrong page names within the edit page

Dockerfile, LICENSE
All earlier versions will remain available under GPLv2.
As TrueWiki can be used as SaaS offering, switching to AGPL is
strongly advised, as that would make mandatory that anyone using
TrueWiki to offer their SaaS, still has to contribute back any
changes to this repository.
The whole idea of this licensing is that it is fine if you want
to use this software (for free), but have at least the decency to
contribute back any features or bugfixes you make. AGPL enforces
this a bit more, especially when used in a SaaS offering.
=> Add: relicense to AGPLv3

truewiki/__main__.py, truewiki/metadata.py, truewiki/storage/git.py, truewiki/storage/github.py, truewiki/storage/local.py, truewiki/web_routes.py
This drasticly speeds up the interface from a user-perspective,
and this is a fancy way of working around the GIL. Ideally we would
use a Git library that is async, which would also resolve this
issue, but with GitPython we are basically 4+ seconds waiting for
"git push" to finish. As that locks the GIL, no other request can
be handled while this is going on.
By moving the git operations to their own process, the main process
can safely continue to serve requests while in the background
git and GitHub are being updated. This is relative safe, as the
application itself doesn't care about git and/or GitHub. Locking
around the use of the out-of-process-git should prevent two
processes trying to access git and/or GitHub.
It is possible that if many people edit pages rapidly, that the
queue of …
=> Add: move all git operations into another process

truewiki/namespaces/category/namespace.py, truewiki/namespaces/file/namespace.py, truewiki/namespaces/folder/namespace.py, truewiki/namespaces/page/namespace.py, truewiki/namespaces/template/namespace.py
If they do not, allow the creation of them by making them linkable.
At least 1 namespace does need to know the language, just to
prevent people from making random languages because they were
feeling like it.
=> Fix: language-folders don't have to exist in namespaces

truewiki/metadata.py, truewiki/storage/git.py, truewiki/storage/github.py
This means that an unexpected exception will terminate the
application completely, instead of hiding away a bit.
=> Fix #75: escalate exceptions from tasks to main thread

Dockerfile, truewiki/__main__.py, truewiki/views/page.py
This uses the same method as we use to detect if the page is a
cache hit when if-modified-since is sent.
For OpenTTD, the total cache-on-disk would be ~150MB, for 10k
pages.
=> Add: cache rendered pages on disk, and serve from there on cache-hit

truewiki/views/page.py
This could happen if the first time a page was loaded, was done
by someone who was logged in. This does update LAST_TIME_RENDERED
for browser if-modified-since caching, but does not write the
file to disk. If a non-logged-in user visit the page after, the
page is not on disk.
=> Fix: only try to load a cache file from disk if the file exists

truewiki/metadata.py, truewiki/views/page.py
If a logged-in user generated a file, LAST_TIME_RENDERED was set,
but the cache on disk is not written. Now if there was an older
version of the cache still on disk, on next request from a visitor
that is not logged-in, the old cache would be served. Solve this
by also removing the cache from the disk, so it cannot do this,
and a new page will be rendered and served.
=> Fix: also delete the cached file on disk

truewiki/namespaces/category/wikilink.py, truewiki/namespaces/file/wikilink.py, truewiki/namespaces/folder/wikilink.py, truewiki/namespaces/template/wikilink.py, truewiki/namespaces/translation/wikilink.py
[[:Folder:en/Bla | Bla]] for example now works.
=> Fix #87: allow spaces before and after the page in wikilink

static/truewiki/truewiki.css, templates/Edit.mediawiki, templates/Error.mediawiki, templates/Login.mediawiki, templates/Page.mediawiki, templates/Source.mediawiki, truewiki/namespaces/base.py, truewiki/namespaces/category/namespace.py, truewiki/namespaces/file/namespace.py, truewiki/namespaces/folder/namespace.py, truewiki/namespaces/page/namespace.py, truewiki/namespaces/template/namespace.py, truewiki/views/sitemap.py, truewiki/web_routes.py, truewiki/wiki_page.py, truewiki/wrapper.py
It requires the --frontend-url to be set, as otherwise we cannot
scope the DuckDuckGo results.
=> Add: search-bar that uses DuckDuckGo to search the wiki

truewiki/views/sitemap.py
Bing.com for one doesn't seem to pick up URLs ending with /.
Hopefully is adding "Main Page" behind it again a solution that
works for it. There isn't really a drawback here, other than an
URL that looks a bit more ugly.
=> Fix: don't strip "Main Page" from sitemap

templates/Edit.mediawiki, truewiki/views/edit.py, truewiki/web_routes.py
With this change, users may specify an edit summary that will be included in the git commit message. Not that unlike wikimedia, the edit summary does not currently support wikimarkup.
=> added edit summaries

templates/Source.mediawiki
The `textarea` field should have the `readonly` attribute so pages that can't be edited will not allow modification of text. Additionally, a text notice has been added above the source text to make it clear to the user why they cannot edit the page, structured similarly to read-only notices on mediawiki.
=> Add: readonly attrib and notice

static/truewiki/truewiki.css, templates/Edit.mediawiki, templates/Error.mediawiki, templates/Login.mediawiki, templates/Page.mediawiki, templates/Source.mediawiki
Alright, this is a small set of changes that has a pretty BIG effect. In short: I've added a bunch of CSS changes to allow graceful handling of mobile clients.
The changes included:
* HTML meta viewport allows for better sizing on different screen DPIs
* `@media` selectors dynamically adjust the CSS to behave differently on desktop and mobile
* Sticky search bar while scrolling (see example picture below)
* Navigation breadcrumbs can horizontally scroll when they grow beyond page width
Some picture examples from the crafty test wiki:
---
Text is easily readable
You can horizontally scroll the breadcrumbs
images fit to screen width
code blocks wrap nicely
sticky search bar
=> Add: Mobile Support

.github/workflows/commit-checker.yml, .github/workflows/testing.yml
- We now use prepared actions, instead of custom shell scripting
- We now validate if testing doesn't leave any annotation (which is often an indication something is wrong)
=> Cleanup some GitHub Workflows a bit

truewiki/views/sitemap.py
Fixes #126
If no other page has been cached yet, the cache folder doesn't
exist yet.
=> Fix #126: cache folder is not created when generating sitemap

truewiki/wiki_page.py
Fixes #127 
When someone access for example "/File", this is not a valid URL.
As such, an error page is generated which calls page_get_language().
This fails, as it is not a valid URL.
Take care of this by doing the minimal validation before calling
the function, and otherwise returning None.
=> Fix #127: page_get_language() expects a valid URL, even for error pages

static/truewiki/truewiki.css
During testing for release, I found a few things that bugged me enough to fix it:
- Padding in header was 6px top, 10px bottom. This is fine for desktop, but on mobile it looked really weird. So changed that for both to 6px both.
- `width: 100%` causes images that are uploaded too big but are suppose to render smaller, to size badly. This would be a huge regression for all wiki's using TrueWiki. So I reverted that part. It will make big images boom on mobile, so we do need to find a solution there. This just isn't that ;)
- Changed the min-width from `992px`, which feels random, to `1020px`, the size of the header. This mostly removes an odd period where we do make the header smaller, before going to full mobile. This works for the default CSS, but any wiki making changes to the header is …
=> Fix: minor CSS touch-ups for mobile support

truewiki/web_routes.py
aiohttp fails to parse the header, and bails out. Capture this
error and just assume the header wasn't set (as it doesn't contain
a value that is useful for us anyway).
=> Fix #164: If-Modified-Since header with an invalid year returned a 500 page

.dockerignore, .gitignore, README.md
These days it is a lot more common to use .venv, and a file .env is
often used to give environment variables for the project.
=> Fix: use .venv over .env for Python virtualenv

static/truewiki/truewiki.css, templates/Edit.mediawiki, templates/Login.mediawiki, templates/Source.mediawiki
Currently only "view" pages were like that, and all other had
the "search" between them. This made styling a real challenge.
Instead now, make sure all pages follow the same flow:
nav, header, search
=> Fix: put <nav> after <header> on all pages

truewiki/__main__.py, truewiki/user/base_oauth2.py, truewiki/user/microsoft.py, truewiki/user_session.py
There are two things Microsoft backend doesn't offer:
- A setting page, to revoke application permissions
- An anonymous email address to base commits on
=> Add: Microsoft as user backend

static/truewiki/truewiki.css
Otherwise people didn't understand you could login and edit pages
for smaller browsers and mobiles.
Now when the window gets too small, the login bar is put below
the rest of the navigation. This uses up slightly more vertical
space, but at least keeps the navigation available for all resolutions.
=> Fix: always show all of the navigation bar, even on mobile

truewiki/__main__.py
run_app() runs the webserver till it is done (read: never), but
since the latest aiohttp it does this in its own eventloop. Read:
the main eventloop is not running inside run_app().
Fix this by explicitly telling to use the mainloop instead.
=> Fix: main eventloop is not running while webserver is

static/truewiki/truewiki.css, templates/Edit.mediawiki, truewiki/storage/git.py, truewiki/storage/local.py, truewiki/views/preview.py, truewiki/views/source.py, truewiki/web_routes.py, truewiki/wiki_page.py
This PR adds basic edit conflict detection based on the modified time of the source page.
~~Whenever a user starts editing a page, the server sets a cookie with the last modified time of that page. When submitting changes, the server then checks the cookie's timestamp against the local file's modified timestamp. If they differ, the change is rejected with a warning.~~
~~Also, while I was in there, I added some html to show the user the last modified time. This time is purely for info, changing it would not effect the comparison, which is based purely on the cookie.~~
**Cookie solution has been replaced with a unique value (either a git hash or a timestamp) included with edit POST forms.**
* Possible future improvement: first try to use the naive `git merge` functionality, to automatically …
=> Add: timestamp-based edit conflict detection

.github/workflows/publish.yml
"docker buildx" doesn't allow to capture the sha256 we need for AWS
deployment, so this approach is not going to work.
This reverts commit 7dc1385ddb1eb7804564c78b466f2fc834bc5779.
This reverts commit a38eb38685736212723a3b12baff9373f8ad5b5d.
=> Revert: [Actions] create image for both linux/amd64 and linux/arm64 (#269)

truewiki/storage/local.py
I noted that the wiki will return a 500 error when A) using the "local" storage option and B) the file does not yet exist.
This was because the way of generating our one-time code (nonce) uses ```python os.path.getmtime(path)``` which returns a `FileNotFoundError` when there is no file at the path.
This fix simply adds a ternary statement that checks if the file exists, and if it doesn't, defaults to a nonce of 0. This still works as a collision-detection mechanism, because if a user creates and submits a new page while another user happens to be working on the same new page, the upstream nonce will resolve to a modified time, which will not match 0 unless the system clock happens to be exactly Jan 1, 1970 -- an occurrence that is expected to be highly unlikely (and if it _does_ occur, …
=> Fix: file collision breaks on files that don't exist

truewiki/storage/local.py
Re: https://github.com/TrueBrain/TrueWiki/pull/291#discussion_r838937074
We actually do NOT want to append the directory to the filename in local.py when we check for existence, because the calling function does this. By wrapping the filename ourselves, we "double-wrap" it. Never a good idea!
=> Fix: filename regression

truewiki/web_routes.py
It calculated the nonce of the new page, rather than the old.
Which is not the intention, as we want to know if the original
page was altered in any way.
=> Fix: renaming files failed on nonce check for local storage driver

truewiki/namespaces/category/content.py
Basically, it always showed templates under "Pages", instead of
under "Templates".
=> Fix: categories didn't group templates correctly

truewiki/storage/git.py, truewiki/storage/local.py
This happened because the commit was still pending, so the nonce
was based on the old hash. Especially if there are a few commits
pending to be processed, this could easily happen.
By switching to modified-time of the file, like the local storage
backend does, we solve this problem. And it is safe, as TrueWiki
cannot scale out anyway for nodes that allow editing.
=> Fix: editing a page quickly after editing told you it was edited by someone else

truewiki/storage/git.py, truewiki/storage/github.py, truewiki/storage/gitlab.py
There was an attempt to prevent that, but sadly, an Event was
used instead of a Lock. This meant that when the first commit
returned, all other pending were going through after that, instead
of one by one.
Lock is fair, as in, the first to acquire is the first to be released.
=> Fix: git-storage-backend could try to commit several commits at once

truewiki/storage/git.py
Because commits are queued, and if remotes are slow, they can
stack up. This makes it possible to add a page and remove one,
before it is committed. In result, when the commit is actually
being executed, it tried to add (or remove) a file that no longer
exists.
Solve this by simply ignoring these events, are they will be
fixed by the next commit in the queue. Sadly, it does mean we
lose a bit of history, but .. yeah, not much we can do about
that.
=> Fix: quickly adding and removing a page crashed the server

truewiki/storage/git.py, truewiki/storage/github.py, truewiki/storage/gitlab.py
Before it assumed the remote branch already existed, and would
use that as template. But if that isn't the case, import the
current data folder, and create the remote branch.
This is mostly meant to allow end-to-end testing, which has
already some content in the data-folder.
=> Fix: import a non-empty data-folder on first-start for github/gitlab storage backend

README.md
The links, both for shields.io as github.com, now use the filename of the workflow, instead of the name inside the workflow.
=> chore(docs): update links in README

.github/dependabot.yml
Some PRs are those that still require other libraries to update for. Till that mooment, they cannot be merged. But closing them is also a bad idea, as then we lose sight of the fact other libraries haven't updated yet.
=> chore(dependabot): allow for more open PRs as some cannot be merged currently

truewiki/user/github.py
authorize_url is the only URL that is client-facing, and should remain github.com. All other URLs are the ones that need rewriting.
=> fix(github): authorize_url should not be rewritten

.github/workflows/end-to-end.yml
This caused failures in upload of codecov reports often and a lot.
=> chore(ci): install codecov token to avoid hitting GitHub API rate limits

truewiki/views/page.py, truewiki/web_routes.py
The ETag is a sha256 hash over the fully rendered page. In constrast to Last-Modified, this value is stable between different runs of the server. It only changes when there is an actual content change.
=> feat(cache): send an ETag header with rendered pages for better caching capabilities
